// apps/demo-angular/src/app/player/player.component.ts
import {
	AfterViewInit,
	Component,
	ElementRef,
	OnInit,
	ViewChild,
} from '@angular/core';
import { HTMLRumblePlayer, RumblePlayerService } from '@rumble-player/rp';

import { fakePlaylist } from '../../config/dummyAudioData.config';

@Component({
	selector: 'rumble-player-player',
	templateUrl: './player.component.html',
	styleUrls: ['./player.component.scss'],
})
export class PlayerComponent implements OnInit, AfterViewInit {
	public player: RumblePlayerService;

	@ViewChild('playerHTML')
	playerHTML: ElementRef<HTMLRumblePlayer> | undefined;

	// playerHTML: HTMLRumblePlayer = new HTMLRumblePlayer();

	public eventsHistory: string[];

	constructor() {
		this.eventsHistory = [];
		this.player = new RumblePlayerService();
		this.player.setPlaylistFromUrls(fakePlaylist);
		// this.ref.nativeElement.appendChild(this.playerHTML);
	}

	ngOnInit(): void {
	}

	togglePlayer() {
		if (this.player.isPlaying) {
			this.player.pause();
		} else {
			this.player.play();
		}
	}

	ngAfterViewInit() {
		if (this.playerHTML) {
			console.log(this.playerHTML)
			this.playerHTML.nativeElement.setPlayer(this.player);
		}
	}
}

<button>
	<a routerLink="spotify">Page 2</a>
</button>
<form>
	<input style="display: inline" type="url" [value]="RSSLink" />
	<button (click)="setRSS()">SET</button>
	<input
		style="display: inline"
		type="url"
		[value]="rate"
		(change)="setRate($event)"
	/>
	<button (click)="playerService.rate = this.rate">SET Rate</button>
	<input
		style="display: inline"
		type="url"
		[value]="volume"
		(change)="setVolume($event)"
	/>
	<button (click)="playerService.volume = this.volume">SET Volume</button>
	<button (click)="playerService.unloadAll = !playerService.unloadAll">
		Unload all
	</button>
	<input type="submit" style="display: none" />
</form>

<br>
<br>
<br>
<br>
<h2>Using rumble-player tag</h2>
<div class="playerContainer" #playerContainer>
	<rumble-player #playerHTML> </rumble-player>
</div>
<br>
<h2>Using custom container (rumble element)</h2>
<div #myCustomContainerDefault></div>
<br>
<h2>Using custom container (classic HTML)</h2>
<div #myCustomContainerCustom></div>
<br>
<br>
<br>
<br>
<br>


<!-- <rs-demo-play-button></rs-demo-play-button> -->

<button (click)="togglePlayer()">click me to toggle play/pause</button>
<button (click)="addSong()">click me to Add song to the playlist</button>
<button (click)="playerService.shuffle = true">shuffle playlist</button>
<button (click)="playerService.shuffle = false">unshuffle playlist</button>
<button (click)="playerService.loop = true">loop</button>
<button (click)="playerService.loop = false">disable loop</button>
<br />
Current state: {{ playerService.isPlaying ? 'playing' : 'not playing' }} <br />
Current index: {{ playerService.index }} <br />
Current position: {{ playerService.position | number: '1.1-1' }} <br />
<hr />

<h2>Playlist:</h2>

<ol>
	<li *ngFor="let song of playerService.playlist; let index = index">
		<ul
			[ngStyle]="
				song.loaded
					? { 'background-color': 'green' }
					: { 'background-color': 'red' }
			"
		>
			<li>
				<a [href]="song.file">File</a> &nbsp;<strong
					*ngIf="playerService.index == index"
					>[selected]</strong
				>
			</li>

			<li>loaded: {{ song.loaded || false }}</li>
			<li>valid: {{ song.valid || false }}</li>
			<li>duration: {{ song.duration | number: '1.1-1' }}</li>
			<li>position: {{ song.position | number: '1.1-1' }}</li>
			<li>playing: {{ song.howl?.playing() || false }}</li>
		</ul>
	</li>
</ol>
<hr />

<h2>History:</h2>
<ol>
	<li *ngFor="let event of eventsHistory">
		{{ event }}
	</li>
</ol>

// apps/demo-react/src/app/player.tsx
import * as React from 'react';
import { RumblePlayerService, HTMLRumblePlayer, LinearBar, SimplePlayButton, GenericVisual } from '@rumble-player/rp';
import { fakePlaylist } from '../config/dummyAudioData.config';
import { ControlButton, Tasks } from './buttons/controls-button';

interface IProps {
}

interface IState {
  isPlaying?: boolean;
  index?: number;
  player?: RumblePlayerService,
  position?:number
}

function Line(props){
  const {value, index , player} = props
  return(
    <li key={value + index.toString()}>
      <ul>
        {player.index === index?
          <li><a href={value.file}>File</a> &nbsp;<strong >[selected]</strong> </li> :
          <li><a href={value.file}>File</a> &nbsp;</li>}
        <li>position: {value.position ? value.position.toPrecision(2) : 0 }</li>
        <li>playing: {value.howl?.playing()}</li>
      </ul>
    </li>
  )
}


export default class Player extends React.Component<IProps, IState>{
  constructor(props) {
    super(props);
    this.state={
      isPlaying: false,
      index:0
    }

  }
  private containerRef = React.createRef();
  private player = new RumblePlayerService();
  private playerHTML = new HTMLRumblePlayer();

  componentWillMount(){}
  componentDidMount = () => {
    this.playerHTML = new HTMLRumblePlayer()
    this.player = new RumblePlayerService()
    this.player.setPlaylistFromUrls(fakePlaylist);

    this.playerHTML.setPlayer(this.player)
    this.setState({player:this.player})
    const linearBar: LinearBar = new LinearBar();
    const simplePlayButton: SimplePlayButton = new SimplePlayButton();
    const BUTTONS = [] as GenericVisual[]
    ['play','pause','stop','next','prev'].forEach(value => {
      BUTTONS.push(new ControlButton(value,Tasks[value]))
    })
    //const myPlayButton: ControlButton = new ControlButton('play',Tasks['play']);

    const visualChildren: GenericVisual[] = [...BUTTONS,
      linearBar
    ];
    this.playerHTML.setVisualChildren(visualChildren);
    console.log(this.containerRef.current as HTMLDivElement);
    (this.containerRef.current as HTMLDivElement).appendChild(this.playerHTML);
    console.log(this.containerRef.current as HTMLDivElement);
    console.log(this.playerHTML);
  }

  togglePlayer = () => {
    	if (this.player.isPlaying) {
    		this.player.pause();
    		this.setState({isPlaying:false})
    	} else {
    		this.player.play();
        this.setState({isPlaying:true})
    	}
  };

  render(){
    const isPlaying = this.player.isPlaying
    const player = this.state.player
    return(<div>
      <br />
      <button onClick={this.togglePlayer}>click me to toggle play/pause</button>
      <hr />
      <br />
      <br />
      Current state: {isPlaying ? 'playing' : 'not playing'}
      <br />
      Current index: {this.state.index} <br />
      <hr />
      <div ref={this.containerRef as React.RefObject<HTMLDivElement>}>
      </div>
      <hr />
      {player?<ol>
        {player.playlist.map((value,index) => {
          // return <p key={value + index.toString()}>{value}</p>;
          return (
            <Line value={value} index={index} player={player}/>
          )
        })}
      </ol>:null}
    </div>
    )
  }
}
