// apps/demo-react/src/app/components/playlist/Playlist.tsx


import * as React from 'react';
import Service from '../../../Service';
import { Song } from '@rumble-player/service';
import Track from '../track/Track';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface PProps {
}

interface PState {
  isHome: boolean;
  defaultImage: string;
}

export default class Playlist extends React.Component<PProps, PState>{
  constructor(props) {
    super(props);
    this.state ={
      isHome : true,
      defaultImage: 'https://i.scdn.co/image/ab67706f00000003c414e7daf34690c9f983f76e'
    }
  }
  static contextType = Service
  componentDidMount() {
    console.log(this.context)
  }

  render() {
    if (this.state.isHome){

      return (
        <div className={'playlist-container'}>
          <div className={'playlist-header'}>
            <img className={'art'} src={this.state.defaultImage} alt={'ok'}/>


            <div className={'album-details'}>
              <h1>Nom</h1>
              <h2>Nom Album</h2>
            </div>
          </div>
          <div className={'playlist-body'}>
            <Track index={0} song={null} header={true} />
            {this.context.player.playlist.map((song: Song, index) =>
              <Track index={index} song={song} header={false} key={song.id} />
            )}
          </div>
        </div>
      )
    } else {
      return (
        <div className={'playlist-container-1'}>
          <div style={{position: "relative"}} >
            <img className={'art-2'} src={this.state.defaultImage}/>
            <div className={'album-details-2'}></div>
          </div>
        </div>
      )
    }

  }

}

// apps/demo-angular/src/app/spotify/playlist/playlist.component.ts
import {
	AfterViewInit,
	Component,
	ElementRef,
	ViewChild,
} from '@angular/core';
import { PlayerBridgeService } from '../player-bridge.service';

@Component({
	selector: 'rumble-player-playlist',
	templateUrl: './playlist.component.html',
	styleUrls: ['./playlist.component.scss'],
})
export class PlaylistComponent implements AfterViewInit {
	defaultImage =
		'https://i.scdn.co/image/ab67706f00000003c414e7daf34690c9f983f76e';
	image: string;
	@ViewChild('header') header: ElementRef<HTMLDivElement> | undefined;
	@ViewChild('header2') header2: ElementRef<HTMLDivElement> | undefined;

	isHome = true;

	constructor(public bridge: PlayerBridgeService) {}

	ngAfterViewInit() {
		if (this.header) {
			this.bridge.playerHTML.addEventListener('newPlaylist', () => {
				if (this.bridge.playerService.playlist[1].albumArt) {
					const icon = this.header.nativeElement.querySelector('img');
					this.image = this.bridge.playerService.playlist[1].albumArt;
					icon.setAttribute('src', this.image);
				} else {
					const icon = this.header.nativeElement.querySelector('img');
					this.image = this.defaultImage;
					icon.setAttribute('src', this.image);
				}
			});
		}
	}
}

<div class="playlist-container" *ngIf="!isHome">
	<div class="playlist-header" #header>
		<img
			class="art"
			src="{{ this.image ? this.image : this.defaultImage }}"
			(click)="isHome = true"
		/>
		<div
			class="album-details"
			*ngIf="bridge.playerService.playlist.length > 0"
		>
			<h1>
				{{
					bridge.playerService.playlist[bridge.playerService.index]
						.playlistName
				}}
			</h1>
			<h2>
				{{
					bridge.playerService.playlist[bridge.playerService.index]
						.author +
						' #' +
						(bridge.playerService.index + 1)
				}}
			</h2>
		</div>
	</div>
	<div
		class="playlist-body"
		*ngIf="this.bridge.playerService.playlist.length > 0"
	>
		<rumble-player-playlist-item [header]="true" [index]="-1">
		</rumble-player-playlist-item>
		<div
			*ngFor="let song of this.bridge.playerService.playlist; let i = index"
		>
			<rumble-player-playlist-item
				*ngIf="song.valid"
				[index]="i"
				[song]="song"
			>
			</rumble-player-playlist-item>
		</div>
	</div>
</div>

<div class="playlist-container-1" *ngIf="isHome" (click)="isHome = false">
	<div style="position: relative" #header>
		<img
			class="art-1"
			src="{{ this.image ? this.image : this.defaultImage }}"
		/>
		<div
			class="album-details-2"
			*ngIf="bridge.playerService.playlist.length === 0"
		></div>
	</div>
</div>
